name = "cloudflare-script"
main = "src/index.js"
account_id = "c270c42dbc42a6d290963cc38f640aa8"
workers_dev = true
compatibility_date = "2026-02-04"


# Environment variables
[vars]
OPENAI_API_KEY = "${OPENAI_API_KEY}"

